/*
    INSERT CATEGORY DATA
*/
INSERT INTO Category(ID,NAME) VALUES (1,'ELECTRONICS')
INSERT INTO Category(ID,NAME) VALUES (2,'HEALTH')

/*
    INSERT SUB_CATEGORY DATA
*/
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (1,'PHONE',1)
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (2,'TELEVISION',1)
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (3,'Beauty and Care',2)
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (4,'MEDICINES',2)
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (5,'LAPTOP',1)
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (6,'TABLET',1)
INSERT INTO SubCategory(ID,NAME,CATEGORY_ID) VALUES (7,'GAMING',1)



/*
    INSERT PRODUCT DATA
*/
INSERT INTO PRODUCT(NAME,SUB_CATEGORY_ID) VALUES ('XBOX',7)
INSERT INTO PRODUCT(NAME,SUB_CATEGORY_ID) VALUES ('IPHONE',1)


